### ISSUE TITLE
Can't run example, error in main `DioException [connection error]`

### ISSUE THREAD

**Issue by ipackdev** [Duit-Foundation/flutter_duit#146]
**Describe the bug**
Error running example.

**To Reproduce**
1. Pull up the repository
2. Run the example

**Error**

```
Performing hot restart...
Syncing files to device sdk gphone64 x86 64...
Restarted application in 1 370ms.
E/flutter ( 5120): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [connection error]: The connection errored: Connection refused This indicates an error which most likely cannot be solved by the library.
E/flutter ( 5120): Error: SocketException: Connection refused (OS Error: Connection refused, errno = 111), address = localhost, port = 53270
E/flutter ( 5120): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:520:7)
E/flutter ( 5120): <asynchronous suspension>
E/flutter ( 5120): #1      main (package:example/main.dart:63:15)
E/flutter ( 5120): <asynchronous suspension>
E/flutter ( 5120): 
I/example.example( 5120): Compiler allocated 4664KB to compile void android.view.ViewRootImpl.performTraversals()
```

**Dependencies**

```
puro flutter pub get

Resolving dependencies... (1.5s)
Downloading packages... 
  async 2.11.0 (2.12.0 available)
  boolean_selector 2.1.1 (2.1.2 available)
  characters 1.3.0 (1.3.1 available)
  clock 1.1.1 (1.1.2 available)
  collection 1.18.0 (1.19.1 available)
  fake_async 1.3.1 (1.3.2 available)
> flutter_duit 3.0.0 from path .. (was 2.3.0 from path ..)
  flutter_lints 2.0.3 (5.0.0 available)
  http 1.2.1 (1.2.2 available)
  http_parser 4.0.2 (4.1.1 available)
  leak_tracker 10.0.5 (10.0.8 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
  lints 2.1.1 (5.1.0 available)
  matcher 0.12.16+1 (0.12.17 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  path 1.9.0 (1.9.1 available)
  stack_trace 1.11.1 (1.12.0 available)
  string_scanner 1.2.0 (1.4.0 available)
  test_api 0.7.2 (0.7.4 available)
  typed_data 1.3.2 (1.4.0 available)
  vm_service 14.2.5 (15.0.0 available)
  web 0.5.1 (1.1.0 available)
```

**Settings**

```
puro flutter doctor -v

[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.26100.2454], locale ru-RU)
    • Flutter version 3.24.5 on channel stable at C:\dev\tools\puro\envs\stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\dev\sdk\android
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\dev\sdk\java\jdk17\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+13-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.7.6)

[√] Android Studio (version 2024.3)
    • Android Studio at C:\dev\soft\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.5+-12651406-b631.16)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

Briefly:
```
Android Studio Meerkat | 2024.3.1 Canary 4

Flutter 3.24.5 • channel stable

jdk17 (build 17.0.10+13-LTS)

Pixel_3a_API_34_extension_level_7_x86_64
```

**Comment by lesleysin** [comment]
@ipackdev Hello! Thanks a lot for the issue.

I reproduced the issue and here's what happened: the address `http://localhost:8999/components`, which is used to get the component layouts when the application is initialized, failed.

You have two ways to solve this problem:
1. Remove the lines of code in the main function that make the request to the local server.
2. Add a new endpoint to your server application that returns the array components according to the API.
